### ISSUE TITLE
Checkout page header problem

### ISSUE THREAD

**Issue by daviserez** [magecomp/magento2-extra-fee#4]
When you go on the checkout page, there is the search bar with the cart icon displayed that must not be.

It seems to be due to the `<page ... layout="1column" ...>` tag from the `view/frontend/layout/checkout_index_index.xml`. Remove the layout attribute to correct the issue.

**Comment by magecomp** [comment]
No sure where exactly you are facing the issue, you can contribute to the extension to improve it by the way.
