### ISSUE TITLE
PayPal gateway has rejected request. The totals of the cart item amounts do not match order amounts (#10413: Transaction refused because of an invalid argument. See additional error messages for details).

### ISSUE THREAD

**Issue by nitaipanda** [magecomp/magento2-extra-fee#6]
PayPal gateway has rejected request. The totals of the cart item amounts do not match order amounts (#10413: Transaction refused because of an invalid argument. See additional error messages for details).

**Comment by magecomp** [comment]
Issue has been resolved in latest version we released today with some other quick fixes.
Please download.
