### ISSUE TITLE
Configuration image issue

### ISSUE THREAD

**Issue by sakshilakshkar** [magecomp/magento2-extra-fee#8]
Configuration image issue magento 2.3.3 version 
![MagecompextrafeeConfigImageissue](https://user-images.githubusercontent.com/41432032/69940086-64e67280-1507-11ea-8876-3e67659350b0.png)

**Comment by magecomp** [comment]
Thanks for the issue opening, let me update the fix for this issue here.

**Comment by sakshilakshkar** [comment]
Hi SupportTeam,

Can you please update this issue.

**Comment by magecomp** [comment]
Please Update the extension,
